#####################################################################
# PLYNET, http://sourceforge.net/projects/plynet
#####################################################################
#
# Copyright (C) 2010 Jorge I. Zuluaga, C. Hincapie, S. Bustamante,
# N. Mateus, P.A. Cuartas
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the Academic Free License (AFL) version 3.0.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
#
# You should have received a copy of the Academic Free License along
# with this program; if not an online version is available at
# http://www.opensource.org/licenses/afl-3.0.php
#####################################################################
# EXAMPLES MAKEFILE
#####################################################################
clean:
	rm -rf *.dat *~

edit:
	emacs -nw *.py 
